#!/bin/bash
jupyter labextension install jupyterlab-server-proxy
npm install -g nativefier
nativefier --name "VSCode" "http://127.0.0.1:8080/?token=\$(jupyter notebook list | grep 127.0.0.1 | awk -F'=' '{print \$2}' | awk '{print \$1}')"
